### ISSUE TITLE
Typo3SiteConfiguration class breaks on imports with EXT:

### ISSUE THREAD

**Issue by schliesser** [helhum/typo3-config-handling#18]
Thanks for this great tool. It works pretty good. I have an issue with imports in my site configuration and this option form the readme:
```yaml
SYS:
    Objects:
        TYPO3\CMS\Core\Configuration\SiteConfiguration:
            className: Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration
```

In my project i have some imports for some extensions in the sitemap like this:

```yaml
imports:
  - resource: 'EXT:my_jobs/Configuration/Sites/config.yaml'
```

Those both configs together are causing TYPO3 to be unable to load the site configuration and result in an broken frontend and backend:
```
(1/1) #1496585828 Helhum\ConfigLoader\InvalidArgumentException
Could not import mandatory resource "EXT:my_jobs/Configuration/Sites/config.yaml" in "/var/www/html/config/sites/my_project/config.yaml"
```

Relative imports are working correctly, but imports with `EXT:` are breaking.

I want to add the `Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration` to configure the solr extension. :-)
