### ISSUE TITLE
How can I override/remove a setting?

### ISSUE THREAD

**Issue by nicodh** [helhum/typo3-config-handling#9]
The yaml files are concatenated recursively as far as I see. So it seems not possible to override an existing settings with an empty value.

For example the default cacheConfiguration for "cache_pages" is
```
cache_pages:
   backend: TYPO3\CMS\Core\Cache\Backend\Typo3DatabaseBackend
   options:
      - compression: true
```
If I change that in my settings to 
```
cache_pages:
   backend: TYPO3\CMS\Core\Cache\Backend\ApcuBackend
```
I get an error: Illegal option: "compression" for ApcuBackend

So the only possibility I found is to add something like:
`$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['cache_pages']['options'] = [];`
in AdditionalConfiguration.php but this file is auto generated and thus overridden...

Or is there another way to achieve this?
